vim.g.mapleader = " "

vim.keymap.set("n", "<c-k>", "<cmd>wincmd k<CR>", { desc = "Move up", silent = true })
vim.keymap.set("n", "<c-j>", "<cmd>wincmd j<CR>", { desc = "Move down", silent = true })
vim.keymap.set("n", "<c-h>", "<cmd>wincmd h<CR>", { desc = "Move left", silent = true })
vim.keymap.set("n", "<c-l>", "<cmd>wincmd l<CR>", { desc = "Move right", silent = true })
vim.keymap.set("n", "|", "<cmd>vsplit<CR>", { desc = "Split vertical", silent = true })
vim.keymap.set("n", "\\", "<cmd>split<CR>", { desc = "Split horizontal", silent = true })
vim.keymap.set("n", "<leader>w", "<cmd>w<CR>", { desc = "Save buffer", silent = true })
vim.keymap.set("i", "jj", "<Esc>", { desc = "Escape", silent = true })
vim.keymap.set("n", "<leader>h", "<cmd>nohlsearch<CR>", { desc = "Reset search highlights", silent = true })
vim.keymap.set("n", "<leader>+", "<C-a>", { desc = "Increment number", silent = true })
vim.keymap.set("n", "<leader>-", "<C-x>", { desc = "Decrement number", silent = true })

vim.keymap.set("n", "<leader>do", vim.diagnostic.open_float, { desc = "Show diagnostic", silent = true })
vim.keymap.set("n", "<leader>dl", vim.diagnostic.setloclist, { desc = "Diagnostics location list", silent = true })
vim.keymap.set("n", "<leader>dq", vim.diagnostic.setqflist, { desc = "Diagnostics quickfix", silent = true })
vim.keymap.set("n", "]d", function()
    vim.diagnostic.jump({ count = 1, float = true })
end, { desc = "Next diagnostic", silent = true })
vim.keymap.set("n", "[d", function()
    vim.diagnostic.jump({ count = -1, float = true })
end, { desc = "Previous diagnostic", silent = true })

vim.keymap.set("n", "<leader>li", "<cmd>LspInfo<CR>", { desc = "LSP info", silent = true })
vim.keymap.set("n", "<leader>ll", "<cmd>LspStart<CR>", { desc = "LSP start", silent = true })
vim.keymap.set("n", "<leader>lR", "<cmd>LspRestart<CR>", { desc = "LSP restart", silent = true })
vim.keymap.set("n", "<leader>lx", "<cmd>LspStop<CR>", { desc = "LSP stop", silent = true })
